services:
  mongo:
    image: mongo:7
    container_name: cict-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - cict-mongo-data:/data/db

volumes:
  cict-mongo-data:
