import { IPermissionMetadata, Permission } from '../types';

export const PERMISSION_METADATA: IPermissionMetadata[] = [
  {
    value: Permission.VIEW_USERS,
    label: 'View Users',
    description: 'View CMS user accounts and access summaries.',
    group: 'Users',
  },
  {
    value: Permission.CREATE_USER,
    label: 'Create Users',
    description: 'Create new CMS user accounts.',
    group: 'Users',
  },
  {
    value: Permission.EDIT_USER,
    label: 'Edit Users',
    description: 'Edit basic CMS user account details.',
    group: 'Users',
  },
  {
    value: Permission.DELETE_USER,
    label: 'Delete Users',
    description: 'Delete CMS user accounts.',
    group: 'Users',
  },
  {
    value: Permission.SET_USER_STATUS,
    label: 'Set User Status',
    description: 'Activate or deactivate CMS user accounts.',
    group: 'Users',
  },
  {
    value: Permission.VIEW_STUDENT,
    label: 'View Students',
    description: 'View student records and academic assignments.',
    group: 'Students',
  },
  {
    value: Permission.CREATE_STUDENT,
    label: 'Create Students',
    description: 'Create student records and initial credentials.',
    group: 'Students',
  },
  {
    value: Permission.EDIT_STUDENT,
    label: 'Edit Students',
    description: 'Edit student records and academic assignments.',
    group: 'Students',
  },
  {
    value: Permission.SET_STUDENT_STATUS,
    label: 'Set Student Status',
    description: 'Activate, deactivate, or suspend student accounts.',
    group: 'Students',
  },
  {
    value: Permission.VIEW_ACADEMIC_GROUPS,
    label: 'View Academic Groups',
    description: 'View programs, year levels, and sections.',
    group: 'Academic',
  },
  {
    value: Permission.MANAGE_ACADEMIC_GROUPS,
    label: 'Manage Academic Groups',
    description: 'Create and update programs, year levels, and sections.',
    group: 'Academic',
  },
  {
    value: Permission.VIEW_ORGANIZATION,
    label: 'View Organizations',
    description: 'View organization records in admin surfaces.',
    group: 'Organizations',
  },
  {
    value: Permission.CREATE_ORGANIZATION,
    label: 'Create Organizations',
    description: 'Create organization records.',
    group: 'Organizations',
  },
  {
    value: Permission.EDIT_ORGANIZATION,
    label: 'Edit Organizations',
    description: 'Edit organization metadata and public profile fields.',
    group: 'Organizations',
  },
  {
    value: Permission.DELETE_ORGANIZATION,
    label: 'Delete Organizations',
    description: 'Delete organization records.',
    group: 'Organizations',
  },
  {
    value: Permission.VIEW_NEWS,
    label: 'View News',
    description: 'View news items in admin content lists.',
    group: 'News',
  },
  {
    value: Permission.CREATE_NEWS,
    label: 'Create News',
    description: 'Create new news items.',
    group: 'News',
  },
  {
    value: Permission.EDIT_NEWS,
    label: 'Edit News',
    description: 'Edit existing news items.',
    group: 'News',
  },
  {
    value: Permission.DELETE_NEWS,
    label: 'Delete News',
    description: 'Delete news items.',
    group: 'News',
  },
  {
    value: Permission.PUBLISH_NEWS,
    label: 'Publish News',
    description: 'Publish draft news items.',
    group: 'News',
  },
  {
    value: Permission.ARCHIVE_NEWS,
    label: 'Archive News',
    description: 'Archive published news items.',
    group: 'News',
  },
  {
    value: Permission.VIEW_ANNOUNCEMENT,
    label: 'View Announcements',
    description: 'View announcements in admin content lists.',
    group: 'Announcements',
  },
  {
    value: Permission.CREATE_ANNOUNCEMENT,
    label: 'Create Announcements',
    description: 'Create new announcements.',
    group: 'Announcements',
  },
  {
    value: Permission.EDIT_ANNOUNCEMENT,
    label: 'Edit Announcements',
    description: 'Edit existing announcements.',
    group: 'Announcements',
  },
  {
    value: Permission.DELETE_ANNOUNCEMENT,
    label: 'Delete Announcements',
    description: 'Delete announcements.',
    group: 'Announcements',
  },
  {
    value: Permission.PUBLISH_ANNOUNCEMENT,
    label: 'Publish Announcements',
    description: 'Publish draft announcements.',
    group: 'Announcements',
  },
  {
    value: Permission.ARCHIVE_ANNOUNCEMENT,
    label: 'Archive Announcements',
    description: 'Archive published announcements.',
    group: 'Announcements',
  },
  {
    value: Permission.CREATE_MEMBER,
    label: 'Create Members',
    description: 'Add organization members.',
    group: 'Members',
  },
  {
    value: Permission.EDIT_MEMBER,
    label: 'Edit Members',
    description: 'Edit organization members.',
    group: 'Members',
  },
  {
    value: Permission.DELETE_MEMBER,
    label: 'Delete Members',
    description: 'Remove organization members.',
    group: 'Members',
  },
  {
    value: Permission.VIEW_MEMBER,
    label: 'View Members',
    description: 'View organization members in admin surfaces.',
    group: 'Members',
  },
  {
    value: Permission.MANAGE_MEMBER_ROLES,
    label: 'Manage Member Roles',
    description: 'Manage roles or positions for organization members.',
    group: 'Members',
  },
  {
    value: Permission.VIEW_EVENT,
    label: 'View Events',
    description: 'View events in admin content lists.',
    group: 'Events',
  },
  {
    value: Permission.CREATE_EVENT,
    label: 'Create Events',
    description: 'Create new events.',
    group: 'Events',
  },
  {
    value: Permission.EDIT_EVENT,
    label: 'Edit Events',
    description: 'Edit existing events.',
    group: 'Events',
  },
  {
    value: Permission.DELETE_EVENT,
    label: 'Delete Events',
    description: 'Delete events.',
    group: 'Events',
  },
  {
    value: Permission.PUBLISH_EVENT,
    label: 'Publish Events',
    description: 'Publish draft events.',
    group: 'Events',
  },
  {
    value: Permission.CANCEL_EVENT,
    label: 'Cancel Events',
    description: 'Cancel published events.',
    group: 'Events',
  },
  {
    value: Permission.COMPLETE_EVENT,
    label: 'Complete Events',
    description: 'Mark events as completed.',
    group: 'Events',
  },
  {
    value: Permission.JOIN_EVENT,
    label: 'Join Events',
    description: 'Register or join public events.',
    group: 'Events',
  },
  {
    value: Permission.VIEW_EVENT_REGISTRATIONS,
    label: 'View Event Registrations',
    description: 'View student event registrations and attendance details.',
    group: 'Events',
  },
  {
    value: Permission.MANAGE_EVENT_REGISTRATIONS,
    label: 'Manage Event Registrations',
    description: 'Manage student registrations, cancellations, and walk-ins.',
    group: 'Events',
  },
  {
    value: Permission.SCAN_EVENT_ATTENDANCE,
    label: 'Scan Event Attendance',
    description: 'Use QR or manual attendance scanning tools.',
    group: 'Events',
  },
  {
    value: Permission.SUBMIT_CONTENT_FOR_APPROVAL,
    label: 'Submit Content For Approval',
    description: 'Submit draft content into the approval queue.',
    group: 'Workflow',
  },
  {
    value: Permission.APPROVE_CONTENT,
    label: 'Approve Content',
    description: 'Approve submitted content items.',
    group: 'Workflow',
  },
  {
    value: Permission.REJECT_CONTENT,
    label: 'Reject Content',
    description: 'Reject submitted content items with a reason.',
    group: 'Workflow',
  },
  {
    value: Permission.CREATE_ROLE,
    label: 'Create Roles',
    description: 'Create custom roles.',
    group: 'Roles',
  },
  {
    value: Permission.EDIT_ROLE,
    label: 'Edit Roles',
    description: 'Edit custom roles.',
    group: 'Roles',
  },
  {
    value: Permission.DELETE_ROLE,
    label: 'Delete Roles',
    description: 'Delete custom roles.',
    group: 'Roles',
  },
  {
    value: Permission.VIEW_ROLE,
    label: 'View Roles',
    description: 'View role catalog and assignments.',
    group: 'Roles',
  },
  {
    value: Permission.ASSIGN_ROLE,
    label: 'Assign Roles',
    description: 'Assign global or scoped custom roles to users.',
    group: 'Roles',
  },
  {
    value: Permission.VIEW_PROCESS,
    label: 'View Process',
    description: 'View process templates and workflow instances.',
    group: 'Process',
  },
  {
    value: Permission.CREATE_PROCESS,
    label: 'Create Process',
    description: 'Create process templates or workflow instances.',
    group: 'Process',
  },
  {
    value: Permission.EDIT_PROCESS,
    label: 'Edit Process',
    description: 'Edit process templates or workflow instances.',
    group: 'Process',
  },
  {
    value: Permission.COMMENT_PROCESS,
    label: 'Comment Process',
    description: 'Add comments or review notes to workflow instances.',
    group: 'Process',
  },
  {
    value: Permission.APPROVE_PROCESS_STEP,
    label: 'Approve Process Step',
    description: 'Approve or reject steps inside process instances.',
    group: 'Process',
  },
  {
    value: Permission.VIEW_LOGS,
    label: 'View Logs',
    description: 'View system logs and audit activity.',
    group: 'System',
  },
  {
    value: Permission.MANAGE_SETTINGS,
    label: 'Manage Settings',
    description: 'Manage system settings and FAQ content.',
    group: 'System',
  },
];

export const getPermissionMetadata = (): IPermissionMetadata[] => PERMISSION_METADATA;
